# Generated by Django 5.2.7 on 2025-10-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsoredChild',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('guardian_name', models.CharField(max_length=200)),
                ('current_school', models.CharField(max_length=200)),
                ('school_contact_person', models.CharField(max_length=200)),
                ('guardian_phone', models.CharField(max_length=15)),
                ('school_contact_phone', models.CharField(max_length=15)),
                ('academic_report_form', models.FileField(blank=True, null=True, upload_to='academic_reports/')),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Sponsored Child',
                'verbose_name_plural': 'Sponsored Children',
                'ordering': ['-date_added'],
            },
        ),
    ]
