# Generated by Django 5.2.7 on 2025-10-14 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_sponsoredchild'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sponsoredchild',
            options={'ordering': ['full_name']},
        ),
        migrations.RemoveField(
            model_name='sponsoredchild',
            name='academic_report_form',
        ),
        migrations.CreateModel(
            name='AcademicReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(choices=[('Term 1', 'Term 1'), ('Term 2', 'Term 2'), ('Term 3', 'Term 3')], max_length=20)),
                ('year', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='academic_reports/')),
                ('average_grade', models.CharField(blank=True, max_length=5, null=True)),
                ('remarks', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='applications.sponsoredchild')),
            ],
            options={
                'ordering': ['-year', '-term'],
            },
        ),
    ]
