# Generated by Django 5.2.7 on 2025-10-14 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_alter_sponsoredchild_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsoredchild',
            name='county',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
