# Generated by Django 5.2.7 on 2025-10-13 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_contactmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main headline text', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='Optional subheading', max_length=300)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hero/')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube video link (optional)', null=True)),
                ('button_text', models.CharField(blank=True, max_length=50, null=True)),
                ('button_link', models.URLField(blank=True, null=True)),
                ('active', models.BooleanField(default=True, help_text='Only one hero section should be active at a time')),
            ],
            options={
                'verbose_name': 'Hero Section',
                'verbose_name_plural': 'Hero Sections',
            },
        ),
    ]
