# Generated by Django 5.2.7 on 2025-10-14 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_herosection'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Matara Moses Foundation', max_length=150)),
                ('footer_about', models.TextField(default='The Matara Moses Foundation is dedicated to transforming lives through education. We provide access, mentorship, and resources for children across Kenya to achieve their dreams.')),
                ('phone_number', models.CharField(default='+254 712 345 678', max_length=30)),
                ('email', models.EmailField(default='info@mataramosesfoundation.org', max_length=254)),
                ('address', models.CharField(default='Mombasa, Kenya', max_length=255)),
                ('facebook', models.URLField(blank=True, null=True)),
                ('twitter', models.URLField(blank=True, null=True)),
                ('instagram', models.URLField(blank=True, null=True)),
                ('youtube', models.URLField(blank=True, null=True)),
                ('footer_text', models.CharField(default='© 2025 Matara Moses Foundation | Built with ❤️ for a brighter tomorrow', max_length=255)),
            ],
            options={
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
